### ISSUE TITLE
运行错误与可能的修正方案

### ISSUE THREAD

**Issue by WavesMan** [xiaofeiyu0723/ExVR#16]
Win bat运行内容：
```batchfile
(venv) PS C:\Users\diwei\Desktop\Code\ExVR-main> py main.py
Traceback (most recent call last):
  File "C:\Users\diwei\Desktop\Code\ExVR-main\main.py", line 25, in <module>
    import utils.tracking
  File "C:\Users\diwei\Desktop\Code\ExVR-main\utils\tracking.py", line 6, in <module>
    from tracker.hand.hand import initialize_hand,hand_pred_handling
  File "C:\Users\diwei\Desktop\Code\ExVR-main\tracker\hand\hand.py", line 66
    f"{"Right" if hand.classification[0].label == "Left" else "Left"}",  # Handedness label
        ^^^^^
SyntaxError: f-string: expecting '}'
``` 
在将目录文件 `./tracker/hand/hand.py` 原第63行至第73行修改为以下内容即正常运行
```python
        # 确保hand.classification非空
        if hand.classification and hand.classification[0].label:
            handedness_label = "Right" if hand.classification[0].label == "Left" else "Left"

            # 在图像上绘制手部的判断（左手或右手）标签
            cv2.putText(
                rgb_image,
                handedness_label,  # 手部判断标签
                (text_x, text_y),
                cv2.FONT_HERSHEY_DUPLEX,
                FONT_SIZE,
                HANDEDNESS_TEXT_COLOR,
                FONT_THICKNESS,
                cv2.LINE_AA,
            )
        else:
            print("警告：未能识别手部判断信息")
``` 

### 备注
运行采用了虚拟环境运行，稍后具体内容会在Fork分支 [WavesMan:main](https://github.com/WavesMan/ExVR/tree/main) 中上传

**Comment by xiaofeiyu0723** [comment]
Thank you for your feedback. I have fixed this issue. However, this issue didn't occur on my computer; it might be related to the interpreter.
